### ISSUE TITLE
RP-1 ROADMAP

### ISSUE THREAD

**Issue by pap1723** [KSP-RO/RP-0#1052]
### Short Term
- [x] Run a balance test campaign -> Continue to balance
- [ ] Release RP-1 v1.01 for 1.3.1

### Next Steps
- [ ] Prepare release for 1.6.1
  - [ ] Update all Dependencies
  - [ ] RO Update and Improvements (see [RO Issue 2007](https://github.com/KSP-RO/RealismOverhaul/issues/2007)
- [ ] Procedural Avionics Rewrite
- [ ] New Science Development
- [ ] Tutorials
- [ ] KCT Updates (see #965 )
- [ ] MLI Balance Changes (now supported by RealFuels)
- [ ] Prefab Tanks Tooling
- [ ] Battery Balancing
- [ ] Kerbalism Integration
- [ ] CommNet Overhaul -> Real Antennas?? ( @DRVeyl and @MikeOnTea )
- [ ] New Part Upgrade System so upgrades can be selectively applied or not
- [ ] Along with previous, Part Upgrades for Tanks (instead of having to create new tanks for each tier)

**Comment by pap1723** [comment]
Updated in different Issue
