### ISSUE TITLE
Midgame balance changes

### ISSUE THREAD

**Issue by siimav** [KSP-RO/RP-0#1370]
### Lunar snowball nerf

- [x] Flybys - 1 completion only, possibly create as a milestone/record?
- [x] Impactors - keep the 3 but every completion after first having lower reward
- [x] Orbiters - keep the 2 but the second completion having lower reward and tighter orbit requirements
- [x] Landers - 4 completions with lowered rewards after first completion
- [ ]  Require a 30d experiment on third completion and a 90d experiment on fourth one 
- [x]  Add a separate contract for far-side landing with 2 completions

### Science changes
- [x] Significantly reduce the tech node cost of nodes between 1957 and 1961
- [ ] Significantly bump up the tech node cost of everything beyond 1965
- [ ] ~~Reduce the science multiplier for all bodies other than Earth~~
- [x] Reduce the landed science multiplier for Moon, Venus and possibly Mars
- [x] Reduce the number of unique biomes for Phobos and Deimos or eliminate biomes entirely
- [x] HOI-like system where the research rate of nodes is adjusted based on whether the player is ahead or behind the curve

### Repeatable commercial satellite contracts
- [x] Do *something* to prevent grinding them over and over breaking the economy.
Some ideas that have been thrown around:
  - add inflation factor to rewards such that the same amount of payload will pay less later on in the career. Would be based off tech progression, for example.
  - multiply the BP cost of commsat payload, such that just building the commsat takes longer, without increasing the rocket cost
  - [x] add soft cooldowns

### Other changes
- [x] Reduce the max completions on Orbital Return to 2 and lower the advances
- [x] Slightly increase the rewards on early sat contracts that have a single completion
- [ ] Add a contract for Lunar HS re-entry tests
- [ ] Reduce the rewards on atmospheric probe contracts
- [ ] Reduce the advance and/or deadline on first manned orbit
- [ ] Shorten the deadlines on manned Lunar milestones
- [x] Gate Crewed Lunar Landing by Crewed Flyby

**Comment by norcalplanner** [comment]
Adjust maximum science point costs for different levels of R&D complex in conjunction with the post-1965 science cost increase

**Comment by Sumguy62** [comment]
Consider making the science multipliers for high and low in space around phobos and deimos 0, since there are no stable orbits around those bodies irl or with principia.

**Comment by ec429** [comment]
@Sumguy62 but it's still reasonable to get short-duration science from a flyby.  An _unstable_ orbit suffices for things like whole-body radiometry or surface mapping, which are distinct from the science a lander can do.

**Comment by TNT599** [comment]
The first manned orbit should be a shorter deadline in hard difficulty

**Comment by szundi** [comment]
Hello guys, don't make it harder, I am playing first on kind of easy (custom) setup, and almost went backrupt one time. Just make an even harder level. Be easy on the beginners, otherwise you lose audience/people.

**Comment by Rockstar04** [comment]
> Hello guys, don't make it harder, I am playing first on kind of easy (custom) setup, and almost went bankrupt one time. Just make an even harder level. Be easy on the beginners, otherwise you lose audience/people. Think about those kids. ;)

From what I remember from past balancing discussions, the team will always attempt to balance the game fir the "Normal" difficulty setting, and then you as the player can always tweak from that.

**Comment by Bornholio** [comment]
On the topic of moving some of these to milestones. I've always been annoyed by the milestone contracts cluttering my contract windows and making me scroll a bunch just to see to actual mission. find a way to sort them to the end or have them hidden some other way by default.

I don't think taking grindy stuff away is the right thing to do.  I don't do those things and have perfectly fine playthroughs but iff that was my thing then why not.  IRL grindy is normal, 800 black brants.

Changing the tech node cost changes time balance. I'd say change the number of points earned to push flying to more biomes and more missions.  Don't eliminate all biomes on D&P but maybe reduce them.  There are many good IRL reasons to visit.

Eliminating 2-3 of the minor biomes hard to hit biomes would reduce my OCD about getting them and reduce the snowball of hitting them with a hopper.  

Replacing the amount in biomes with the built in deployable and alsep style experiment would be awesome to get people on to manned missions in more depth. lots of good resources for that in stock.

Orbiters should do things. CommNet's on other bodies would also be important missions.  our current orbit body mission is not very demanding. personally love the scansat stuff because of the mapping function.  This forces proper real world missions.

Agree with szundi, don't make the game harder just modify the explosion of mid game points.

**Comment by leudaimon** [comment]
I PRed #1472 to address 
* Reduce the landed science multiplier for Moon, Venus and possibly Mars
* Gate Crewed Lunar Landing by Crewed Flyby
There are also some other changes to science there to reduce biome hunting both on Earth and in Venus/Mars. 
Those changes could probably be compensated on Earth with either more types of supersonic flight, probably crewed, and maybe a returnable mass spectrometer

**Comment by siimav** [comment]
While there's still a couple of good ideas here, I'm closing this since the balance will be completely different with Programs.
