### ISSUE TITLE
RP-0 for KSP 1.0

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RP-0#154]
**Misc work**
- [x] Update Earth biome map ('reach' goal, not strictly required). The Earth's biome map is very dated and not terribly accurate or appealing. A new map should come in 8192/4096/2048 format, and should follow the guidelines here https://github.com/KSP-RO/RSS-Textures/issues/3 .
- [x] Science text! All the old text won't work anymore for obvious reasons. [See here](https://www.reddit.com/r/RealSolarSystem/comments/2o4erh/real_solar_system_crowdsourced_science_logs/). For instruments and what's needed, see #156.

**Plugin work**
- [x] Update avionics plugin
- [x] Remove contracts from plugin

**Contract work**
- [x] Add some basic ContractConfigurator contracts (at the very least, a repeatable sounding rocket contract and a repeatable HSF contract). X-plane contracts would also be good, now that altitude records don't require crew.
- [x] Further contract work per ideas in the contracts issues #65 and #9 and @aw1621107 's Contract Configurator issue #144.
- [x] Increase homeNearby numbers in Contracts.cfg to avoid crash (if we use stock contracts at all).
- [x] Modify the new stock contracts.
- [x] **Balance contracts.**

**Tree work**
- [x] Update our tree changes for the new CTT (will require some reorganization as the 1.0 tree is rather different).
- [x] Move parts as appropriate for the new tree.
- [x] Move engine configs as appropriate for the new tree.
- [x] Add entryCost to engine CONFIGs now that RF supports entry costs.

**Interoperability**
- [x] Update KCT config for new KCT.
- [x] Add CustomBarnKit configs for the various buildings (ends use of NoMoreGrind and of the custom dll).

Anything else?

**Comment by Shurikeeen** [comment]
What do you mean with "X-plane contracts"?

**Comment by NathanKell** [comment]
Like the X-1, X-2, X-3, X-15, that sort of thing.
There should be two sets of speed/altitude/range record contracts: one for uncrewed vehicles, and one for crewed vehicles.

**Comment by KellanHiggins** [comment]
Realized today that I couldn't have a fun time playing RO without RP-0. I wanna see this released and can help.

Poked around a while but I couldn't find where the biome maps are stored. Point me in the right direction and I'll create a new map. Been doing graphic design for years and game programing in Unity for the last two. 

I am gonna keep looking for that map as I have zero experience in modding KSP.

**Comment by NathanKell** [comment]
@KellanHiggins  awesome! Thanks so much. :)

**PSA: KSP 1.0 TESTING RELEASE** https://github.com/KSP-RO/RP-0/releases/tag/v0.00000-testKSP1-0
Try it out and see how it goes!

**Comment by Shurikeeen** [comment]
I could use some help with balancing the contracts. I'm not the best at this stuff :P

**Comment by NathanKell** [comment]
Ok, got the tech tree sorted, though I have to update the engine CONFIG techRequired entries when appropriate.

@Shurikeeen I finally had a chance to look at the contracts. I did some cleanup on the version in the repo--I haven't checked the descriptions for wording/grammar/whatever, but I did replace manned with crewed per RP-0 practice (we talk about crewed and uncrewed spacecraft/missions, and Human Spaceflight, HSF, as the blanket term for all crewed spaceflight).
I also reorganized things a tad, made some changes pursuant to the below, and fixed up how GROUP is used (you declare the group once, and reference it in every contract, as @jrossignol mentioned).

Here's what I'd like you to do if you're willing (and/or other folks, feel free to chip in):
1. A set of altitude and speed records for sounding rockets. Every 10km through 60km, then every 20km through 200km, then every hundred km through 1000km, then every 1000km through 10,000km. For speed, 350, 600, 900, 1200, 1500, 2000, 3000, 4000, 5000. I realize that's a large number, but they can be copy-pasted.
2. A set of altitude and speed records for crewed craft: Every 5km through 40km, every 10km through 100km, every 20km through 200km, then 500km, then 1000km. For speed, the same as above although jumping from 2000 to 5000 and then finally 10,000.

3. A _repeating_ set of sounding rocket contracts, varying based on prestige. Low prestige would be in the 40-100km range, medium in the 100-1000km range, and high in the 1000-5000 range. This is so that people can repeat these contracts for money.

4. A _repeating_ HSF orbital contract (the one right now should be moved to Human Records, and replaced with a repeating version).

Make sense?

**Comment by NathanKell** [comment]
@Shurikeeen Yep, I just wanted to do the above (and write the novel-length comment above >.> ) before launching up KSP to try them out. :)

**Comment by Shurikeeen** [comment]
Yup, I could do those.

**Comment by NathanKell** [comment]
Awesome! :)

**Comment by NathanKell** [comment]
(For now I'm going to leave the existing records contracts enabled, until those are done, to help with early-game progression / sense-of-accomplishment)

**Comment by Shurikeeen** [comment]
By looking at some of the crewed contracts, you don't need to have the "MaxCrew" parameter set to 9999. You can remove it and the contract will say "At least 1 crew" :)

**Comment by NathanKell** [comment]
Ah, good point. That's only that one, feel free to fix.

**Comment by Shurikeeen** [comment]
Should the "Complete Contract" requirement be left? Or should all the contracts be available from the start..?

**Comment by NathanKell** [comment]
@Shurikeeen sorry, I don't recall changing anything there. What do you mean?

**Comment by Shurikeeen** [comment]
@NathanKell Previously there were only like 5 sounding rocket contracts and you need to complete those to get the unmanned orbit and after that you get manned orbit contract and then you get all the contracts. Now when there are a million sounding rocket contracts, what contract unlocks the unmanned orbit contracts etc?

**Comment by NathanKell** [comment]
Oh! I see, sorry, I did miss that entirely.
I suggest having the record contracts be like stock KSP--normally unshown, and autoaccept. Then have a simple "Pass the Karman line" contract, which unlocks orbital. The orbital contract then unlocks all other contracts (both crewed orbital and uncrewed probe)--it should be possible to fly an uncrewed career. :)

**Comment by Shurikeeen** [comment]
@NathanKell That would make sense.

**Comment by NathanKell** [comment]
Cool. I should mention that that is not the line where situation changes to Space Low (that's 130km), but the choice of that is RSS's, rather than reality's, so we should use the Karman line (100km), which needs to be set as an altitude requirement not a reachspace requirement.

Also, while it's probably unwise to do it for our first 1.0 release, I'd love to one day see the Kerbni World First Whatever replaced by the [FAI](https://en.wikipedia.org/wiki/F%C3%A9d%C3%A9ration_A%C3%A9ronautique_Internationale) :)

**Comment by jrossignol** [comment]
Give me an hour or two and I'll throw you guys an example config of how to do the records all in one contract (well, one per type).

**Comment by Shurikeeen** [comment]
@jrossignol Well, I have already the record contracts :P

**Comment by NathanKell** [comment]
@jrossignol you know, I was tempted to tag you on the large post about records contracts, and then I thought "meh, I've poked enough"... :]

**Comment by NathanKell** [comment]
@jrossignol I'd still like to know regardless though, if you're willing. From the PR we still have to do speed records, and I want to try some things regarding detecting lifting flight...(and maybe handle downrange distance too).

**Comment by jrossignol** [comment]
Yup, kids are in bed now, shouldn't take me very long to get something to you.  The main reason is I wanted to steer you away from the AltitudeRecord requirement - I need to document its limitations - specifically that KSP only records a fixed set of altitude records (specifically, the ones from the stock contract).

There's other benefits of course, such as easier maintenance.

**Comment by NathanKell** [comment]
I <3 easier maintenance, it's very true! :)

**Comment by jrossignol** [comment]
Here you go:
```
CONTRACT_TYPE
{
    name = RecordTest

    title = Set an altitude record of @targetAltitude.Print()m.
    description = TODO
    synopsis = TODO
    completedMessage = TODO

    autoAccept = true

    prestige = Trivial

    targetBody = HomeWorld()

    // Can only have one active
    maxSimultaneous = 1

    // Contract rewards
    rewardFunds = 100.0

    // Ultra high weight makes sure that these get auto-generated
    weight = 1000.0

    DATA
    {
        type = List<int>

        altitudes = [ 10000, 20000, 30000, 40000, 50000, 60000, 80000, 100000, 120000, 140000, 160000, 180000, 200000, 300000, 400000, 500000, 600000, 700000, 800000, 900000, 1000000, 1000000, 2000000, 3000000, 4000000, 5000000, 6000000, 7000000, 8000000, 9000000, 10000000 ]
    }

    // Break this into two steps to work around ContractConfigurator#260
    DATA
    {
        type = float

        index = RP0_SoundingAltitudeIndex
    }

    DATA
    {
        type = int

        targetAltitude = @altitudes.ElementAt(@index)
    }

    PARAMETER
    {
        name = ReachState
        type = ReachState

        minAltitude = @/targetAltitude
    }

    BEHAVIOUR
    {
        name = IncrementIndex
        type = Expression

        CONTRACT_COMPLETED_SUCCESS
        {
            RP0_SoundingAltitudeIndex = RP0_SoundingAltitudeIndex + 1
        }
    }

    REQUIREMENT
    {
        type = Expression

        expression = @/index < @/altitudes.Count()
    }
}
```

How it works:
* The RP0_SoundingAltitudeIndex is a sort of global variable that gets saved in the "persistent data  store" (a ScenarioModule).
* On contract initialization, RP0_SoundingAltitudeIndex is used to index into the array of records.
* On contract completion, RP0_SoundingAltitudeIndex is incremented

**Comment by NathanKell** [comment]
Oooh, very neat! Should be applicable to speed as well quite neatly. I don't suppose there's a way to have the rewards scale with the record?

**Comment by jrossignol** [comment]
Oh right, I was going to mention that!

You could do any number of things, here's a few to get you thinking:
```
rewardFunds = 100.0 + @index * 100.0
```
```
rewardFunds = Pow(@targetAltitude, 0.5)
```
```
rewards = [ 100, 200, 500, 600, ...]
rewardFunds = @rewards.ElementAt(@index)
```
I wish I had a log() function to offer here too (I'll add that for the next version, even if you guys aren't using it I should have it).

**Comment by NathanKell** [comment]
Hah! :)

**Comment by NathanKell** [comment]
To balance contracts I'm going to play a game with absolutely no contracts, hard difficulty, and see how many funds it takes to reach each milestone and unlock each node. That should give us a good estimate as to how much money the player should be making. I will release another preview so that others can do the same thing.
**NOTE** to do this I have deleted everything in the Contracts folder except RemoveStockContracts.cfg and installed Contract Configurator (so it disables them all). So that's how you can too.

**Comment by KellanHiggins** [comment]
Just installed the pre-release on a recently installed RO. RSS didn't load at start and it wiped my settings right away. Not sure what could be causing it. Running on Windows Bootcamp on my mac. Was working fine as RO before.

**Comment by NathanKell** [comment]
That's _really_ weird (and sorry about that!) Do you have a log from it?

**Comment by NathanKell** [comment]
(I should point out I'm running RSS/RO/RP-0 with no issues, though I am on master for RO, not the last release)

**Comment by NathanKell** [comment]
Quick runthrough until first orbit:
999600 after first successful flight, 14 science, plus extras
997500 after second, all basic nodes but aero unlocked (with extra 300f subtracted). Leaves 2.7 science which can combine with shots over water (effectively doubling science) to research the aero node.

Now the big costs, parts for Vanguard (or Juno/R-5).
Sat: 2400
US guidance 2000
LS guidance 4000
Att jet 500
AJ10 3000
Sgt 100
X405 13000
RD-103 17000
That means entry for Vanguard style is 25mil, and for Juno I style it's 24. We really need to make new tank diameters/lengths have entry costs... (Vanguard should be ~65 mil).

967200 after 3 orbital shots (1 succeeded) - 24,000 for entry costs and ~2100 per launcher.

This means 3 things, I think.

1. We should have some sort of "launch your first vessel" contract with a 1000 fund advance and something like 5000 payout.

2. The Karman line contracts should be visible and not auto-accept, so players see how much money they'll get. The uncrewed one should have an advance of about 2000, and a payout of about 30,000 (or 70,000 if we increase research costs as appropriate). The crewed one...dunno yet.

3. The orbit contract should pay out enough that you can start purchasing Atlas/R-7 level parts, so maybe 100,000 for first orbit and something like 20k each (plus 3000 advance) for early repeating uncrewed orbital contracts...

**Comment by Shurikeeen** [comment]
@NathanKell Noted!

**Comment by Shurikeeen** [comment]
@NathanKell "First Launch" is not a parameter it seems. I could improvise with a altitude parameter though.

**Comment by Shurikeeen** [comment]
@NathanKell Should the science rewards be removed?

**Comment by NathanKell** [comment]
@Shurikeeen  Yeah, the rewards should only be funds and rep. As to first launch, I agree that alt is workable, 3km is probably best for that then. That's reachable in a Bonanza, and easily reachable by rocket.

An additional concern which I had forgotten about: The Soviet path involves a pad upgrade as well as researching probably 50,000 funds or more of parts.
Here's my new radical idea for that: leave the Karman line payout in the 30k range, and give the First Orbit contract a _large_ advance and a _small_ payout, something like 100-150k or more in advance, and only 50k on complete. But give it an expiration of 2 years once picked and make it un-cancellable once picked ( @jrossignol is that possible? ). That will make it represent the "commitment" to orbit a satellite in the IGY, and the funding boost necessary to do so.

**Comment by jrossignol** [comment]
Actually, for first launch you can always just use `situation = FLYING` with ReachState.  The old FirstLaunch parameter died when the underlying stuff in KSP changed in 1.0, and I never bothered to recreated.

Uncancellable would be:
```
    cancellable = false
```
:wink:

**Comment by NathanKell** [comment]
aaaand I get my just deserts for not actually reading the params. :]
Sorry. :]

**Comment by NathanKell** [comment]
@Shurikeeen in trying to balance the record contracts ( b703007181ab54c7efccef1e80a7b63629f80670 ) I realized that it would be much, much simpler if they were in the form above. I hate to ask you to redo them since you already spent so much effort on them, but could you redo them as four contracts, per the form @jrossignol offered above? (i.e. one each for crewed/uncrewed and alt/speed). That would let us balance them very easily by changing the formula, rather than changing the rewards on every contract.
Also, autoaccept contracts probably shouldn't have advances or (since there's no expiration) failure results... :) (in effect you'd just see the advance for the next contract as part of the reward of the previous contract, it'd just be confusing...)

**Comment by Shurikeeen** [comment]
@NathanKell I guess I could do that, but you could use Notepad++'s "replace" function to change a line on all the documents you have open.

**Comment by NathanKell** [comment]
@Shurikeeen Yes. But that doesn't work for having rewards scale with the record, only having one set reward across all records. What I'm talking about is, say, the fund reward for alt records being something like 1000 + sqrt(alt) * 2
If it's a pain, don't worry about it. :)

**Comment by Shurikeeen** [comment]
@NathanKell I can't figure out how to use the thing @jrossignol showed. :P

**Comment by NathanKell** [comment]
No problem. :)

**Comment by jrossignol** [comment]
The only thing I'd be careful about the current solution is performance related.  Contract Configurator generates contracts in the background so that when KSP asks it for a new contract it can return one right away (it was done this way to fix some lag issues that used to occur).  It also means that if KSP asks for a contract and one isn't ready, it won't get generated.  This is usually fine, but sometimes KSP is picky about whether it decides to generate contracts.  Anyway, the two things to keep an eye out for in your testing:
 1. Do you always get the first contract on a new save?  This is the time I'd be most concerned - as it's having to go through many contracts before it'll offer the right one, and if KSP decides not to ask for a contract, you won't see it show up.
 1. Does it not flow from one contract to the next when doing a bunch of altitude records together.  I'm less concerned here as I think there's enough gap between the altitudes that there's no way that the contract pre-loader isn't getting to the right one in time.

So just make sure to keep an eye on those in testing and you should be okay with the current solution.

**Comment by NathanKell** [comment]
Converted to the procedural form in 8fe582e36ee3c208330eb1113b4750a310433d21

**Comment by Shurikeeen** [comment]
Is there a list of mods what the tech tree uses? I found that some of the nodes are empty.

**Comment by Shurikeeen** [comment]
Is CTT still required? It seems to add lots of empty nodes.

**Comment by batuhantasli** [comment]
I agree with Shurikeeen. It means more work to do but I think a tech tree specifically designed for RP-0 would be better. Actually early tech tree seems fine so we can just use it as a start. We can also use some late tech nodes for future technologies (Near Future stuff for example) and provide a longer gameplay and give people chance to try technologies that are not present. (Someone stated this idea before actually, but forgot who, sorry)

**Comment by NathanKell** [comment]
CTT is required and does add empty nodes. However, our approach to CTT is mostly to cannibalize it, as you're seeing with the early nodes; nonetheless using it as a base saves an incredible amount of work since the structure is *mostly* fine and also it already has the nodes created and given icons.
Certainly we *intend* to support more mods, and more stuff later on in the tree, it just takes a while...

**Comment by Warp11** [comment]
There's a spelling mistake in the RSSKopernicus.cfg. One of the Venus Biomes reads Lakshmi Plnaum. I'm pretty sure it's supposed to be Planum. Can someone correct that? And I need to know that to get the science report files right. Thx

**Comment by Shurikeeen** [comment]
Heads up, the contracts are causing a huge FPS drop. With RP-0 and ContractConfigurator I get 15 FPS on the pad with 1 part but when I remove them I get 90 FPS.

**Comment by Shurikeeen** [comment]
Should there be added more contracts for the outer planets?

**Comment by NathanKell** [comment]
I'd say right now our focus should be on early-game stuff, to have a decently playable experience through 1965 or so. So I'd suggest playtesting for now rather than adding more contracts.

**Comment by Shurikeeen** [comment]
Is there a list of all the mods the tech tree supports?

**Comment by NathanKell** [comment]
@Shurikeeen I missed this, sorry. The list of what RP-0 supports is on the front page of the repo, with the addition of a sprinkling of AIES and KW engines.

As all boxes are checked, I am closing this! Woo!
