### ISSUE TITLE
1.0.5 To-Do FASA Changes

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RP-0#388]
I took a quick look at how the FASA parts through the Apollo landing appear in FASA, I'm happy to see that I can agree with where most parts are and their general pricing. In 1.0.5 I plan to start a new career play (to take advantage of many of the new contracts that have been added!) So I will probably add to this thread as I notice things I want to change. Feel free to express your opinion about FASA RP-0 interaction here.

One general point. Currently some tank costs are a bit 'out of whack' with that a similarly capable ProcTank can provide. @NathanKell, will there be adjustments to ProcTank prices at some point (I find it a little odd that a Default or Fuselage tank costs the same as a BalloonCryo one) or is it fair to place tank prices in line with the price of a similarly capable ProcTank?

- [x] Move the J-2 from the Early Hydrolox to the Hydrolox node. In my install the Hydrolox node is empty. I will need to look at the tree.yaml to see if anything else is already in that node for certain other mods.

- [x] Copy the config of the Gemini or Apollo fuel cell to the stock Fuel Cell/Fuel Cell Array parts. I haven't seen TACLS update to 1.0.5 yet (in CKAN) so it also might make sense to use the TACLS fuel cell rather than the Gemini/Apollo config. ((Change to be made in RO))

- [x] Move FASA Adv. Gemini E.S. to the same place as the normal one, which is in Electrics.

- [x] Move the Saturn I-B tank from Improved Solids to Mature Orbital. 

- [x] Price Saturn I-B tank to ~1800, which is the price of a ProcTank of the same volume.

- [x] P&P Saturn S-iB fins. Currently fairly expensive. Perhaps 10-50 price?

**Comment by stratochief66** [comment]
@winged7 If you have any other FASA suggestions I'd be interested. You could probably get most of the things on my list done in 1/10 the time it would take me, so I figured it is my interest for you to see them as well. :P

**Comment by winged7** [comment]
1, 4, 5, 6 done.

Not sure about 3. what you mean by FASA Adv. Gemini E.S. - Escape System?

**Comment by stratochief66** [comment]
@winged7 

Equipment section. This puppy, I think:
https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/FASA/RO_FASA_Other.cfg#L635

**Comment by winged7** [comment]
Tell me exactly which part (part name) you want to move to electrics.

**Comment by stratochief66** [comment]
FASAGeminiEngineFuel2

**Comment by winged7** [comment]
It is already in electrics:
https://github.com/KSP-RO/RP-0/blob/master/tree.yml#L2018

**Comment by stratochief66** [comment]
Yeah, sorry. That is what I get for trying to ID the part when I'm asleep.

It looks like both parts (FASAGeminiUtilityPack and FASAGeminiEngineFuel2) are already on that node in the RP-0 tree. They are the exact same part in practice (at least, they should be) but one models the engine as RCS, the other as an engine. An issue with TACLS causes the engine version to be troublesome.

You're right (of course) they are both on the same tech node. I just created a PR to copy the pricing as well.

https://github.com/KSP-RO/RP-0/pull/390

**Comment by stratochief66** [comment]
Nearly done! I am just waiting for a new TACLS do perform some TACLS fixes.

**Comment by stratochief66** [comment]
I just noticed that the last undone thing had already been done, by me, in june :)

So, all done! Now to find new bugs (ones that I can fix).

The FASA colliders issue affects a number of issues with 1.0.5. The Saturn V interstage ring and LES all have violent and destructive streams now...
