### ISSUE TITLE
Current To-Do List

### ISSUE THREAD

**Issue by pap1723** [KSP-RO/RP-0#680]
I have started a to-do list of things that I know need to be completed, I was going to keep this locally, but it doesn't make any sense to do that.

Contract Modifications
- [x] Look at contract payouts for 3/4 Comms Network
- [x] Why did GEO Comms Network fire on NK stream so early? Should be 80's TDRS type contract
- [x] Lunar Sample Return mission longer Duration? In line with Lunar Human Flyby

For the next major RP-0 release:
 - [x] Add LR43-NA-3 Engine Config (earliest Atlas Booster MA-1)
 - [x] Add LR43-NA-5 Engine Config (earliest Atlas Sustainer MA 1)
- [x] Add S-3 engine Config (earliest Thor booster MB-1)
- [x] Fix the S1.5400 series
- [x] Launchpad and other building tiers revamp
- [x] Tree OMG tree!
- [x] take advantage of KSP 1.2's auto-unlock thing for equivalent parts.
- [x] Rescale science based on experiments available
- [x] Roll in new science parts as well
- [x] ~~use Sigma88's new science capping system to allow adding new biomes and decrease whackamolity.~~ We have Kerbalism now
- [x] Have our own difficulty presets
- [x] PARTUPGRADE functionality for RCS and Solid Tech Upgrades
- [x] PARTUPGRADE functionality for RCS Fuel Types
- [x] Set all generic RCS to default to Nitrogen to avoid unlock issues.
- [x] Look at increasing the data received from a TF failure
- [x] Standardize all Comms distances, rates and costs
- [x] Disable stock hibernation (or swap to it, stripping out RP-0 avionics hibernation?)
- [x] fix max pressures on parts (HIGH PRIORITY - no Venus for you, otherwise)
- [x] Disable admin building
- [x] ~~Cryogenic as addon to a tank.~~ MLI layers
- [x] Kill cockpits for space
- [x] Facility and astronaut and KCT upgrade upkeep.
- [x] Remove size constraints on proc parts/fairings
- [x] make RCS use engine configs.
- [x] Entry costs for parts through 1962 or so.
- [x] EntryCosts for tanks moved to the newStart node.
- [x] Rescale contract payouts.
- [x] Start with 0 crew?
- [x] Move payload resources to RP-0.
- [x] ~~Remove stock and mod agents.~~ WHY?
- [x] Training
- [x] Fix Aerobee/WAC
- [x] Raise price of engine R&D
- [x] Per-part KCT cost modifiers (like mk1pod)

Semi-medium
- [x] Launch costs and payout rebalance
- [x] Upgrade electric TANKs via PartUpgrade nodes.
- [x] ~~Rep-gating milestones~~ Never going to happen
- [x] ~~TestFlight support for non-engine parts~~ Highly doubt this is ever getting touched
- [x]  Crew R&R and retirement
- [x] More tank levels
- [x] More avionics rings
- [x] add PARTUPGRADE mass changes to proc fairings parts.

Medium term:
- [x] Manufacturing lines, quick version (using ScrapYard)
- [ ] Launch costs, again, but with more feeling
- [x] Training for kerbals
- [ ] Budget systems, reputation-based funding, etc.
- [ ] Programs (leverage Strategia)
- [ ] Allow using rockets you've built to complete contracts "offscreen", or even set aside the VAB to build them to. So you don't have to manually fly sounding rocket contracts.

Long term:
- [x] Write a preprocessor for entry cost things (or do it from the tree yaml processor) for maintainability / ease of adding new stuff.
- [x] Unlock costs for proc part sizes
- [ ] Tutorials
- [ ] ROize and RP0ize KSPedia
- [ ] Consider deprecating stages from proc parts and instead use something like SSTU exclusively (or the system @Saabstory88 was working on).

See also: https://github.com/KSP-RO/RealismOverhaul/issues/1242

**Comment by NathanKell** [comment]
Cool! Gonna edit in a bit.
Btw the 210 Isp is I presume sea level Isp for it.

**Comment by pap1723** [comment]
I would assume that is the case with the isp. I could not find any other information on that engine except from Alternatewars

**Comment by NathanKell** [comment]
There, plopped over some stuff from RO:#1242.

**Comment by glilienthal** [comment]
I wonder whether you (we?) should before that already release what is there. I find it quite playable, and think it'd really help more people to enjoy what is there. But mabye I don't have so high expectations ;)

**Comment by NathanKell** [comment]
Oh yes, as it says that's for the next major release. We still plan to release for 1.2 ASAP via the Pap-Contracts branch.

**Comment by glilienthal** [comment]
:) !

**Comment by NathanKell** [comment]
Added S1.5400 fix per Papscussion and also the PARTUPGRADE stuff  #657

**Comment by pap1723** [comment]
Added the automatic part unlock feature into the mod. I think I got all of them, but we will probably come across some while we are playtesting.

**Comment by pap1723** [comment]
Added Comms balancing

**Comment by NathanKell** [comment]
Questions:

1. Disable Admin Building for now?
2. Remove all agents other than our own?

**Comment by pap1723** [comment]
1. Yes, I think that is a good idea
2. Let's hold off on that until we add a few extra agents. We only have the FAI one, the others that are used are actually CC agents as of now.

**Comment by NathanKell** [comment]
Added hibernation and Venus.

**Comment by NathanKell** [comment]
I've merged down to master.

**Comment by jdub3350** [comment]
Would it be out of line to suggest that the "supported mods" list be updated with the next release to reflect what all is part of the new tree?

**Comment by pap1723** [comment]
@jdub3350 I think that is a good idea

**Comment by Bornholio** [comment]
science spreadsheet link so i don't loose it again
https://docs.google.com/spreadsheets/d/1tEm2aR1fSOVhjBjkgt6mrYLYC20c-FzCKK3pqW9N2hU/edit#gid=0

**Comment by pap1723** [comment]
This has all been surpassed, or discussed in future issues.
