### ISSUE TITLE
Contracts To-Do List

### ISSUE THREAD

**Issue by pap1723** [KSP-RO/RP-0#710]
This is a running list of the contracts I still want / need to add to RP-0.

## SOUNDING ROCKETS
- [ ] Get Payload X to Altitude X (I haven't had time to play-test with the different sizes of pads)

## EARTH SATELLITES
- [ ] Remove the First Polar Sat Contract. It is unnecessary with the First Sun Synchronous satellite contract accomplishing the same thing. They feel like duplicated contracts in a play-through.
- [ ] GPS Constellation or GLONASS Constellation of 24 satellites in multiple orbits and planes
- [ ] Satellites to take pictures of Random Waypoints on the map (can be thought of as military spy satellites or commercial imaging satellites)
- [ ] Integrate contracts for SCANsat

## LUNAR / INTERPLANETARY SATELLITES
- [ ] Scientific focused satellites that require specific types of orbits and to maintain them for a specific amount of time in order to complete the contract
- [ ] Integrate contracts for SCANsat
- [ ] Fix Atmospheric Probe contracts to get into the parts of the atmosphere that would be dangerous without proper design and protection (they can be completed currently by dipping into atmosphere only a very small amount)

## FUTURE PROJECT
These are just because I want to create them and this is what I got started in KSP modding to create.
Essentially these contracts will replace the RP-0 contracts that exist now (the player will choose with the first contract). So each side will have flavor missions that they can choose to basically accomplish the same thing as the RP-0 contracts now. So instead of Lunar Impact, the Soviets will get a Luna Program Impact Contract. The US would get the Ranger Program.
- [ ] Full US Historical Contracts Pack
- [ ] Full Soviet Historical Contracts Pack

## FUTURE-FUTURE PROJECT
- [ ] Create a full fledged US Historical Campaign (similar to how BARIS/BAPSM operate)
- [ ] Create a full fledged Soviet Historical Campaign (similar to how BARIS/BAPSM operate)
- [ ] Use the above Campaigns to allow a true Race into Space with @ec429 RtS mod

**Comment by ppboyle** [comment]
Should I keep a list here too, or open a new issue?  Also, your first item there should be pretty much done now. :)

**Comment by pap1723** [comment]
@ppboyle I fully support you looking into the plane contracts (while reserving the right to do none of that) :)

I recommend taking a look at Giving Aircraft a Purpose for some ideas possibly as well. It is a VERY well-thought out and executed contract pack: http://forum.kerbalspaceprogram.com/index.php?/topic/129208-contract-pack-giving-aircraft-a-purpose-gap-129-air-flights-tours-coast-guard-sts-oct-28-2016/
