### ISSUE TITLE
TO-DO's So We Don't Forget for Next Release (Keep adding to this list)

### ISSUE THREAD

**Issue by pap1723** [KSP-RO/RP-0#931]
- [x] Add SSTU Tanks to JSON / Database and Include Idents with Proc Tanks as well as ECM's (this is already in the release version, but it will be overwritten when the new files are generated.
     -SSTU-A-Tank-I
     -SSTU-A-Tank-II
     -SSTU-A-Tank-III
     -SSTU-A-Tank-III-Balloon
     -SSTU-A-Tank-IV
     -SSTU-A-Tank-SM-I
     -SSTU-A-Tank-SM-II
     -SSTU-A-Tank-SM-III
     -SSTU-A-Tank-SM-IV

- [x] Add tooling for the SSTU Fairings (If we can read fairing size)

- [x] Add tooling for the rest of the SSTU tanks

- [x] Add tooling for the SSTU Decoupler

- [x] Orphans Tech Node for parts without a home

- [ ] Tooling and Proper costs for Pre-fab tanks
     - Cristi from the Discord is working on getting us the costs
     - I believe in order to implement this, we will need to add a PartModule to the pre-fab tanks. New tooling code will have to be written to read the PartModule. The PartModule will have the diameter, length, shape and tank type.

- [x] Fix the ridiculous cost of the 20in X-Ray Probe

- [ ] Communications
     - We need to review all CommNet distances with respect to the Tracking Station upgrades
     - NK had talked about switching RT antennas to a relay design, but I don't know what this means (anyone? edit: is this for control delay possibly? https://github.com/KSP-RO/RealismOverhaul/commit/4a12ffd1d3f89ba82bb1b7e7126bda1ddcb81310)

- [x] Unpressurized Cockpits
    - These have been fixed multiple times, but they were never added to the spreadsheet so the configs have been overwritten. Need to be added to the JSON

- [x] Add a MAX function to the Sounding Rocket contract payouts to fix the neverending increasing amount that can be exploited with low tech

- [x] Look into EVA / EVA Suits being a PARTUPGRADE that functions after a certain Technology is Researched
    - Based on #411 we should be able to set a flag to all vessels adding `noAutoEVAAny = True` and then removing that with the proper tech unlock

- [x] Look at RCS PartUpgrades to fix duplicates

**Comment by Bornholio** [comment]
"Next Release" :) , May i pretty please have an Orphans Node in tech also.  I'll PR it next weekend assuming i have one

**Comment by Bornholio** [comment]
MODS by support for each https://docs.google.com/spreadsheets/d/17ulTbJnPmblfDJGvcCpdOPLJTStC7Y1NQvOwVKG3TVg/edit#gid=0  just started filling in

**Comment by pap1723** [comment]
Updated with Sounding Rocket Contract Payouts

**Comment by Bornholio** [comment]
https://docs.google.com/spreadsheets/d/1hrpiE9eptRayV0w4n6snKXFPlRexeQkAXHQAbfYZJpM/edit#gid=0  Antenna stuff

**Comment by pap1723** [comment]
Updated in multiple places.
