### ISSUE TITLE
v1.10 MINOR RELEASE for KSP 1.4.5

### ISSUE THREAD

**Issue by pap1723** [KSP-RO/RP-0#976]
With all of the work and activity that is going on and the conversations that have been had in Discord over the last few weeks, I wanted to outline the plan for releasing the next 2 versions of RP-1. There will be the first release, which will be considered, a "Minor" release and will bring the game up to 1.4.5 and then a "Major" release which will have a lot of harder to implement changes that will take some time.

We are looking for help to get these things accomplished and would love whatever help you can give us to finish them up.

**Must Haves**

- [ ] Update of Dependencies to 1.4.5
    - [ ] CustomBarnKit (works, needs CKAN update for 1.4.5)
    - [ ] Ven's Stock Part Revamp (needs release for 1.4.5)
        - There is a working version of VSR kept up to date by @Kerbas-ad-astra and I have asked for permission to fork it and release it through CKAN
    - [ ] Kerbal Construction Time (SEE BELOW - needs CKAN update for 1.4.5)
    - [ ] TestFlight (SEE BELOW - needs release for 1.4.5)
    - [ ] TACLS (needs CKAN update for 1.4.5)
- [x] Reorganization of the early game
    - [x] Using @siimav new Downrange abilities for CC, we will add support for these contracts
    - [x] Finalize the organization of the First Launch -> Karman Line -> SR Contracts -> First Orbit
        - See Issue #956 for more details
    - [x] Lunar Contract Modification
        - See Issue #966 for more details
- [ ] Continued organization and clean-up / support for parts in the Tech Tree
    - See #969 #962 #960 #945 #943 #931 
- [x] EntryCostModifiers for Parts improved
    - @leudaimon has started on a lot of this for Engines, but is looking for support
- [x] Reorganize Difficulty Levels
    - We currently balance for Hard, Instead, let's balance for moderate and make normal a little easier and hard as much more difficult
    - Have each level of difficulty allow reverts and autosaves because Kraken
- [ ] Clean up Old Issues
- [x] Reduce entryCosts and partCosts on all QoL parts (lighting, structural, ladders, etc)
- [ ] Manual and Tutorial Videos
 
**Nice to Haves**
- [ ] KCT Updates (see #965)
    - [x] Configurable Cost-Per-Click for Rush Build
    - [x] Ability to choose pad level when building new one (see #935)
    - [x] Changing point unlocks to be science point based, not node based
    - [x] Allow gating of facility upgrades by tech
    - [x] Prevent rolling out to a pad being upgraded
    - [x] Show total points invested in each VAB / R&D
    - [ ] Ability to decrease upgrade points
    - [x] Allow training on a part being researched
    - [ ] Change Rollout to be Construction -> Integration / Assembly -> Testing / Rollout
- [ ] MLI Changes (not allowing infinite cooling for so cheap)
- [x] Science Changes (see #974 )
- [ ] Pricing and Tooling for Prefab Tanks (see #962)
- [ ] Balance Battery Mass and Costs
- [ ] Mid-Tier Part Node Fill Out
    - Chaka Monkey, Bluedog, RN
- [x] Tips on Loading Screens (takes 10 minutes to load, might as well learn things)
    - [x] Write more tips

**Pie in the Sky (most likely next major release)***
- [ ] Kerbalism Integration
- [ ] CommNet Overhaul
    - Antenna Part Upgrades
- [ ] Battery Upgrades
- [ ] Procedural Avionics Rewrite
- [ ] KCT Updates (see #965)
- [x] Rebalance of Crew Training (should be expensive)
- [ ] Update to 1.6
- [ ] Part Upgrades or Additional Tanks for Procedural Tanks (see #930)
- [x] Integration of @ec429 awesome new engine system
- [ ] Late Game Node Fill In
    - Near Future and Chaka Monkey

**Comment by Bornholio** [comment]
Must Haves:
Abandon Vens and absorb as cfg :P
Hard settings default revert/load/save
Note on training/retirement settings to reduce payouts by 5% if not used


NTH:
Price tanks as if they were Proc, both costs and entry
General reduction in entry and costs on most parts, specifically all the QOL parts like structural, lighting, misc parts. 
Price batteries as if they were proc  both costs and entry
Get AIES to update
Mid tier part node fill out

Pie:
Part Upgrades for antennas
Part Upgrades for Batteries
Late Game part fill in (focus on NF first)

**Comment by pap1723** [comment]
Removed a lot of your stuff and integrated it into the above. I don't understand Training note.

**Comment by NathanKell** [comment]
Thanks to our lord and master @sarbian CBK now supports setting per-TS-level patch vis levels. This means that we can make the starting TS only show your position, not any orbit line. An upgrade to that shows your orbit line, and only third level allows patched conics.

**Comment by NathanKell** [comment]
Note that the above is very closely coupled to KCT gating upgrades by tech, in other words we gate having patched conics by *tech* (i.e. you need to research how to go to the moon) not just money.

**Comment by Theysen** [comment]
A few inputs from my side.

ModuleManager patching significantly increased since 1.4+, alone that will help quite tremendously in the future. 

Beware with using the continued Ven's Stock Part Revamp. The Poodle engine got switched to a - well, quite subjectively strange - engine model and deprecated the old SPS inspired engine. We use that (in RO I guess) to represent quite a few other engines. It would be best to kind of revert that change and use the current model in RO.


Also: Please think about balancing Soviet Roleplays to be somewhat doable. Right now it's impossible to do anything significant. But that is a thing for the future I guess!

**Comment by ppboyle** [comment]
One thing that'd be nice to have is a predicted rollout cost for each of the available pad levels the player has, while in the VAB/SPH.  Right now rollout costs are a bit opaque and this would at least let the player see how changes to the rocket impact the total as they build it.  Probably a NTH.

**Comment by Jerre122** [comment]
If you click on the "show build list" in the VAB you can change the launchpad in the VAB and the predicted rollout cost will change as well.

**Comment by NathanKell** [comment]
I thought even those costs might be bugged in the VAB. It's a problem.

**Comment by Kerbas-ad-astra** [comment]
@Theysen, the SPS-like model is still in the same place (VenStockRevamp/Squad/Parts/Propulsion/Poodle), so any parts using it in a MODEL node are still OK; the only thing that changed is that Ven made a new model for the Poodle ("PoodleS2NTR") that looks more like the old stock model (and I've since made some changes to its node positions to avoid causing trouble with intersecting models when 'upgrading', since the new model is taller than the stock model).

**Comment by pap1723** [comment]
Procedural SRB
Tooling support for SRB

**Comment by laukejas** [comment]
Where can I find to download this release? I scoured through this git, and I was unable to find it. Could someone give me a link, please? Thank you.

**Comment by MikeOnTea** [comment]
There is no release to download, this was a proposal and the issue is still open as you see.

**Comment by laukejas** [comment]
Oh, I see. Sorry. Does the earlier version (for 1.3.1) work with KSP 1.4.5? Something to use until the next official release of RP-1?

**Comment by Bornholio** [comment]
NTH:

  - [ ] Part files moved to parts folder:

- avionics.cfg
- chakamonkey_engines.cfg
- LinearRCS.cfg
- NewRFTanks.cfg
- PartHacks.cfg
- ProcCosts.cfg
- Tantares_Engines.cfg

**Comment by pap1723** [comment]
Does ChakaMonkey and Tantares Engines actually do anything?

**Comment by pap1723** [comment]
I ask because I have never opened them and Tantares was completely revamped after that file was built.

**Comment by Bornholio** [comment]
if they are not in the browser then i think maybe, but regardless they are just TL and cost values and shouldn't be seperate patches

**Comment by leudaimon** [comment]
the warning I do get everytime is related to RT:
[WRN 2019-25-02 17:25:09.506] 1 warning related to GameData/RemoteTech/RemoteTech_RLA_Probes.cfg

**Comment by pap1723** [comment]
Closed and moved to #1052
